### ISSUE TITLE
Route middleware returning function timeout

### ISSUE THREAD

**Issue by si-harps** [mikestaub/serverless-express#17]
Hi, in the following scenario the request times out (10.01s - user defined timeout), any ideas?

```javascript
// analytics.routes.js

const express = require('serverless-express/express');
const router = express.Router();

const controller = require('./controllers');
const { has } = require('./lib');

router.get('/analytics/conversion-views', has.permission('canViewAnalyticsDashboard'), controller.conversionViews);

module.exports = router
```

```javascript
// lib/has.js

function permission(permission) {

        // Able to log permission argument

	return function(req, res, next) {

                // Never gets called!

		if (!req.session)
			return res.sendStatus(401)

		const session = req.session.get({ plain: true })
		const roles = extractRoles(session);
		const permissions = extractPermissions(session);

		if (!match(permission, roles, permissions)) 
			return res.sendStatus(401)

		return next()
	}
}

module.exports = { permission }
```

**Comment by iliasbhal** [comment]
You should export the express app

```js
const express = require('serverless-express/express');
const app = express(); // <- 1. create an express app
const router = express.Router();

const controller = require('./controllers');
const { has } = require('./lib');

router.get('/analytics/conversion-views', has.permission('canViewAnalyticsDashboard'), controller.conversionViews);

app.use(router); // <- 2. use the configured router
module.exports = app; // <- 3. export the app
```

**Comment by si-harps** [comment]
@iliasbhal - thanks, I already exported the Express app way upstream. Each of these route files is required at run time so uses the express singleton previously cached by the commonJS loader on start.

The above example is purely api route definitions so no need to initialise the app again.

On a side note, i think i may have discovered the problem which may be completely unrelated (DB Connection Timeout). Will post here when confirmed

**Comment by si-harps** [comment]
@iliasbhal - I updated the snippet above. I'm just exporting the router at this point, app exported from a different file once all routes have been required dynamically. The issue turned out to be a DB connection timeout so completely unrelated. Doh! Thanks for your reply anyway :)
