### ISSUE TITLE
How do I use this with webpack

### ISSUE THREAD

**Issue by adeshrd** [mikestaub/serverless-express#18]
In the readme, it is mentioned to add following in handler file:

```
const handler = require('serverless-express/handler')
const app = require('path/to/your/express/app')

exports.api = handler(app)
```

Now, my express app is generated from webpack so the express app is not exported directly.

How can I use this with webpack generated bundle file?

**Comment by iliasbhal** [comment]
You can import the bundled version of simply set the index file as the entry point in your webpack config
