### ISSUE TITLE
Question: Universal Logging

### ISSUE THREAD

**Issue by jpgilchrist** [mikestaub/serverless-express#29]
Is there a best practice with this library for logging? Each service provider seems to do logging differently. I.e., Azure uses `context.log`. Hopefully a simple question with a simple answer. Perhaps, is there a way to access the context in the request? I.e., something like `req.context` (which I know doesn't exist as I've tried it).

**Comment by mikestaub** [comment]
Unfortunately, that is out of the scope of this module. I personally use winston to create a logger class that can support multiple transports.
