### ISSUE TITLE
const express = require('serverless-express/express') doesn't work

### ISSUE THREAD

**Issue by PaulRBerg** [mikestaub/serverless-express#3]
Using your README code:

```const express = require('serverless-express/express')```

I get this error: `Error: Cannot find module 'serverless-express/express'` The module is definitely installed.

**Comment by iliasbhal** [comment]
I'll check that this afternoon for you.

**Comment by iliasbhal** [comment]
should work now !

type again in your terminal 
``` npm install --save serverless-express```

**Comment by PaulRBerg** [comment]
Thanks! It's fine.
