### ISSUE TITLE
aws-serverless-express like init process

### ISSUE THREAD

**Issue by samikarak** [mikestaub/serverless-express#55]
Hello guys,

we would like to convert from aws-serverless-express to serverless-express, since this package probably will be more maintained and up to date. Therefore, we need to know how we can duplicate the initialization behavior shown in the code below:

- using binaryMimeTypes
- connecting to db before starting express app

We want to be able to connect beforehand, so as lambda does not try to connect to the db on every request.

```
export {};

require('source-map-support').install();
const awsServerlessExpress = require('aws-serverless-express');
const expressApp = require('./dist/app');
const binaryMimeTypes = ['*/*'];
const server = awsServerlessExpress.createServer(expressApp, null, binaryMimeTypes);

module.exports.index = async (event, context) => {
  if(!expressApp.get('dbConnected')) await expressApp.initDB();
  return await awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise;
}
```

As you can see we used the promise function of awsServerlessExpress.proxy to be able to connect before we started the express server.

**Comment by mikestaub** [comment]
I was actually considering deprecating this library and advising devs to use aws-serverless-express as it seems to be more popular. Why do you think this will be a better option for you? I wrote this before the other library was available

**Comment by samikarak** [comment]
Hello, When I click on the GitHub link on NPM, I get rerouted to this library. Also, somewhere I thought I read that aws-serverless-express will be deprecated for this one. I don't know, maybe there is a mix up. So aws-serverless-express is the better choice ?

**Comment by samikarak** [comment]
Hello, 
I have mixed up something. Never Mind.
